#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
MEC-2.1 | Batch 2 manual curation layer.
Hand-reviewed interpretations of snippet evidence (identity-matched, noise-rejected).
Every record cites host + date-basis. Evidence = Advertised (snippet) unless noted.
This file is the SINGLE SOURCE for batch-2 curated offers; merge step applies it
over the auto-draft (auto candidates kept only where explicitly trusted below).
"""
TODAY = "2026-09-27"
EV = "Advertised (snippet, 27/09)"
EVO = "Advertised (official-page snippet, 27/09)"
EVN = "Documented (news/review snippet, 27/09)"

# seller-host interpretation notes for transparency
H = {
    "aks": "allkeyshop-tracked (price-comparison aggregator)",
    "ggd": "gg.deals-tracked (price-comparison aggregator)",
    "scd": "smartcdkeys-tracked (price-comparison aggregator)",
}

CURATED = {
  # ═════════ AI/SaaS ═════════
  "SKU-AI002": {"official": {"seller": "OpenAI", "price": 240.0, "cur": "USD", "note": "annual plan NOT offered officially (help.openai: no annual billing) — 12-month prepaid = gray construct at 12×$20", "evidence": EVN},
      "offers": []},
  "SKU-AI033": {"official": {"seller": "OpenAI", "price": None, "cur": "USD", "note": "ChatGPT Plus annual does not exist officially (help.openai 27/09: 'we do not support annual billing')", "evidence": EVN},
      "offers": []},
  "SKU-AI003": {"official": {"seller": "OpenAI", "price": 8.0, "cur": "USD", "note": "ChatGPT Go $8/mo (openai.com announcement snippet)", "evidence": EVO},
      "offers": []},
  "SKU-AI004": {"official": {"seller": "OpenAI", "price": 200.0, "cur": "USD", "note": "$200/mo per openai.com announcement; pricing-page snippet also shows 'From $100/month' tier wording — direct verification pending", "evidence": EVO},
      "offers": []},
  "SKU-AI007": {"official": {"seller": "Anthropic", "price": 100.0, "cur": "USD", "note": "Max tiers $100/$200 per month (third-party reviews consistent; official page not retrieved)", "evidence": EVN},
      "offers": []},
  "SKU-AI010": {"official": {"seller": "xAI", "price": None, "cur": "USD", "note": "SuperGrok price not cleanly retrieved; third-party review references 'SuperGrok Lite $10/mo' — unverified", "evidence": EVN},
      "offers": []},
  "SKU-AI011": {"official": {"seller": "DeepSeek", "price": None, "cur": "USD", "note": "third-party comparison cites $6/1M-in $30/1M-out (model unspecified; conflicts with known deepseek-chat rates) — direct verification pending", "evidence": EVN},
      "offers": []},
  "SKU-AI013": {"official": {"seller": "Midjourney", "price": 10.0, "cur": "USD", "note": "Basic $10/mo ($96/yr = $8/mo annual) — docs.midjourney.com plan table", "evidence": EVO},
      "offers": []},
  "SKU-AI014": {"official": {"seller": "Midjourney", "price": 30.0, "cur": "USD", "note": "Standard $30/mo — docs.midjourney.com plan table", "evidence": EVO},
      "offers": []},
  "SKU-AI029": {"official": {"seller": "Microsoft", "price": 20.0, "cur": "USD", "note": "Copilot Pro $20/mo (third-party review consistent with known official price; official page not retrieved)", "evidence": EVN},
      "offers": []},
  "SKU-AI046": {"official": {"seller": "GitHub", "price": 10.0, "cur": "USD", "note": "Copilot Pro $10/calendar-month — docs.github.com licenses page", "evidence": EVO},
      "offers": []},

  # ═════════ Gift Cards ═════════
  "SKU-GC008": {"official": None,
      "offers": [{"seller": "Eneba", "role": "Marketplace", "price": 23.67, "cur": "USD", "note": "PSN 25 USD (USA) 'From $25.00 -5% = $23.67'", "evidence": EV}]},
  "SKU-GC048": {"official": None,
      "offers": [{"seller": "Eneba", "role": "Marketplace", "price": 19.04, "cur": "USD", "note": "PSN 20 USD (USA) 'From $20.00 -5% = $19.04' (same listing family as 25 USD card)", "evidence": EV}]},
  "SKU-GC009": {"official": None, "offers": [],
      "state_note": "Lead-only: gg.deals result was 50-EUR card; no 25-EUR price retrieved this run"},
  "SKU-GC010": {"official": None,
      "offers": [
        {"seller": "gg.deals Keyshops", "role": "Price comparison", "price": 54.18, "cur": "USD", "note": "PSN 50 EUR (Spain) keyshops current price", "evidence": EV},
        {"seller": "cdkeyprices-tracked", "role": "Price comparison", "price": 50.83, "cur": "USD", "note": "'€50 PSN GC from $50.83'", "evidence": EV}]},
  "SKU-GC052": {"official": None,
      "offers": [
        {"seller": "Eneba", "role": "Marketplace", "price": 34.81, "cur": "USD", "note": "PSN 50 USD (AR) — BELOW face; listing marked 'sold out' at retrieval (premium-market outlier)", "evidence": EV},
        {"seller": "K4G (cardkudo-tracked)", "role": "Marketplace", "price": 67.91, "cur": "USD", "note": "PSN 50 USD Argentina ~$67.91 — ABOVE face value (regional-arbitrage premium market; rate $1.35/USD)", "evidence": EV}],
      "state_note": "AR-market structural finding: cards trade ABOVE face (regional price arbitrage)"},
  "SKU-GC011": {"official": None, "offers": [],
      "state_note": "Lead-only: no valid SAR-denominated PSN price retrieved this run"},
  "SKU-GC053": {"official": None, "offers": [],
      "state_note": "Lead-only: no valid Bahrain price retrieved this run"},
  "SKU-GC031": {"official": {"seller": "Sony (via G2A plan table)", "price": 24.99, "cur": "USD", "note": "PS+ Essential 3 months $24.99 (G2A-cited official plan pricing)", "evidence": EVN},
      "offers": []},
  "SKU-GC032": {"official": None, "offers": [],
      "state_note": "Lead-only: Xbox Game Pass gift results were wallet cards, not membership"},
  "SKU-GC057": {"official": None,
      "offers": [{"seller": "allkeyshop-tracked", "role": "Price comparison", "price": 9.34, "cur": "USD", "note": "Xbox GC 10 USD $9.34 (+$1.18 fee line) — below-face listing", "evidence": EV}]},
  "SKU-GC058": {"official": None, "offers": [],
      "state_note": "Lead-only: 15-USD Xbox card price not isolated this run"},
  "SKU-GC074": {"official": None,
      "offers": [{"seller": "dlcompare", "role": "Price comparison", "price": 50.0, "cur": "USD", "note": "Google Play 50 USD at face $50.00", "evidence": EV}]},
  "SKU-GC076": {"official": None,
      "offers": [
        {"seller": "Kinguin", "role": "Marketplace", "price": 96.0, "cur": "USD", "note": "Google Play 100 USD US '-4%' (≈$96 implied from discount %)", "evidence": EV},
        {"seller": "dlcompare", "role": "Price comparison", "price": 100.0, "cur": "USD", "note": "face-value listing", "evidence": EV}]},
  "SKU-GC093": {"official": None,
      "offers": [
        {"seller": "Eneba", "role": "Marketplace", "price": 48.54, "cur": "USD", "note": "Razer Gold 50 USD 'From $48.54'", "evidence": EV},
        {"seller": "sodagift", "role": "Reseller", "price": 47.0, "cur": "USD", "note": "Razer Gold $50 at $47.00 (estimated lowest)", "evidence": EV}]},
  "SKU-GC094": {"official": None,
      "offers": [{"seller": "livecards", "role": "Reseller", "price": 98.95, "cur": "USD", "note": "Razer Gold 100 USD (Global) $98.95", "evidence": EV}]},
  "SKU-GC097": {"official": None,
      "offers": [{"seller": "vividgold.africa", "role": "Regional reseller", "price": 11.0, "cur": "USD", "note": "Spotify $10 US card at $11 — ABOVE face (regional markup outside US)", "evidence": EV}]},
  "SKU-GC098": {"official": None,
      "offers": [{"seller": "vividgold.africa", "role": "Regional reseller", "price": 32.0, "cur": "USD", "note": "Spotify $30 US card at $32 — above face", "evidence": EV}]},
  "SKU-GC095": {"official": None, "offers": [],
      "state_note": "No valid offer: Netflix GC results were spam/fraud pages (rejected); GCs trade at face via official retail"},
  "SKU-GC096": {"official": None, "offers": [], "state_note": "Not searched (no query matched this run — inherited Lead-only)"},
  "SKU-GC099": {"official": None, "offers": [], "state_note": "Lead-only: Roblox GC eneba page returned no numeric price in snippet"},
  "SKU-GC100": {"official": None, "offers": [], "state_note": "Lead-only (same listing family as GC099)"},
  "SKU-GC101": {"official": None, "offers": [], "state_note": "Lead-only (same listing family as GC099)"},
  "SKU-GC001": {"official": None, "offers": [], "state_note": "Lead-only: eneba Steam 20 EUR page retrieved without numeric price in snippet"},
  "SKU-GC002": {"official": None, "offers": [], "state_note": "Lead-only (same listing family)"},
  "SKU-GC003": {"official": None, "offers": [], "state_note": "Lead-only (same listing family)"},
  "SKU-GC004": {"official": None, "offers": [],
      "state_note": "Noise-rejected: allkeyshop/smartcdkeys results were KINGUIN gift cards (not Steam) — documented as channel-behavior data point (Kinguin €50 GC ≈ $49.45-56.52)"},
  "SKU-GC007": {"official": None, "offers": [], "state_note": "Lead-only: turgame SAR page returned no numeric price"},
  "SKU-GC035": {"official": None, "offers": [], "state_note": "Noise-rejected: 'Eneba gift card' results (not Steam)"},
  "SKU-GC036": {"official": None, "offers": [], "state_note": "Noise-rejected: same"},
  "SKU-GC038": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC040": {"official": None,
      "offers": [{"seller": "Kinguin", "role": "Marketplace", "price": 5.66, "cur": "USD", "note": "REFERENCE POINT ONLY — Steam USD 5 card at $5.66 (100-USD card price not in snippet; Kinguin 'Steam top-up' category verified live)", "evidence": EV, "identity_flag": "adjacent-denomination"}]},
  "SKU-GC041": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC043": {"official": None,
      "offers": [{"seller": "Eneba", "role": "Marketplace", "price": 23.50, "cur": "USD", "note": "Steam Wallet 20 EUR (EUROPE) 'From $23.50' — EUR denomination, above face (adjacent identity to 20-USD-EU SKU)", "evidence": EV, "identity_flag": "adjacent-identity (EUR card)"}]},
  "SKU-GC045": {"official": None, "offers": [], "state_note": "Lead-only (same listing family as GC043)"},
  "SKU-GC050": {"official": None, "offers": [], "state_note": "Lead-only: kinguin PSN 100 USD page returned no numeric price"},
  "SKU-GC022": {"official": None, "offers": [], "state_note": "Lead-only: Apple 100 AED UAE — no numeric price in snippets"},
  "SKU-GC059": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC060": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC061": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC066": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC067": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC068": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC069": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC070": {"official": None, "offers": [], "state_note": "Noise-rejected: bitrefill results were Eneba GCs (crypto premium $107 per $100 documented as channel-behavior data)"},
  "SKU-GC072": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC078": {"official": None, "offers": [], "state_note": "Lead-only: Amazon GCs trade at face officially; no discount channel documented"},
  "SKU-GC080": {"official": None, "offers": [], "state_note": "Lead-only (same)"},
  "SKU-GC082": {"official": None, "offers": [], "state_note": "Lead-only (same)"},
  "SKU-GC084": {"official": None, "offers": [], "state_note": "Lead-only (same)"},
  "SKU-GC090": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC091": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GC092": {"official": None, "offers": [], "state_note": "Lead-only"},

  # ═════════ Game Top-up ═════════
  "SKU-GT002": {"official": None, "offers": [], "state_note": "No valid offer: Free Fire results were noise (dairy-news/tiktok pages)"},
  "SKU-GT003": {"official": None, "offers": [], "state_note": "No valid offer (same query family)"},
  "SKU-GT005": {"official": {"seller": "In-game store (topuplive-documented)", "price": 4.99, "cur": "USD", "note": "325 UC official $4.99", "evidence": EVN},
      "offers": []},
  "SKU-GT006": {"official": {"seller": "In-game store (topuplive-documented)", "price": 9.99, "cur": "USD", "note": "660 UC official $9.99", "evidence": EVN},
      "offers": [{"seller": "G2A (GalaxyLink key)", "role": "Marketplace", "price": 26.61, "cur": "USD", "note": "660 UC G2A listing — ABOVE official (gray top-up premium, not discount)", "evidence": EV}]},
  "SKU-GT007": {"official": {"seller": "In-game store (topuplive-documented)", "price": 24.99, "cur": "USD", "note": "1800 UC official $24.99", "evidence": EVN},
      "offers": [{"seller": "G2A (GalaxyLink key)", "role": "Marketplace", "price": 28.68, "cur": "USD", "note": "1800 UC G2A -7% off $28.68 — still above official", "evidence": EV}]},
  "SKU-GT009": {"official": None, "offers": [], "state_note": "Lead-only: MLBB results carried no isolated 172-diamond price"},
  "SKU-GT010": {"official": None, "offers": [], "state_note": "Lead-only (same)"},
  "SKU-GT012": {"official": None,
      "offers": [{"seller": "loaded.com", "role": "Authorized reseller", "price": 19.49, "cur": "USD", "note": "Valorant 2050 VP (20 USD pack) $19.49, 3% off face", "evidence": EV}]},
  "SKU-GT015": {"official": None,
      "offers": [{"seller": "sythe.org (forum resellers)", "role": "Gray forum market", "price": 6.99, "cur": "USD", "note": "2800 V-Bucks $6.99 (gray forum) — far below official; account/top-up method, high risk", "evidence": EV}]},
  "SKU-GT035": {"official": None,
      "offers": [{"seller": "sythe.org (forum resellers)", "role": "Gray forum market", "price": 2.49, "cur": "USD", "note": "1000 V-Bucks $2.49 (gray forum) — reference for pack family", "evidence": EV, "identity_flag": "adjacent-denomination (1000 pack)"}]},
  "SKU-GT017": {"official": None, "offers": [], "state_note": "Lead-only: Roblox 800 Robux — no isolated price in snippets"},
  "SKU-GT018": {"official": None, "offers": [], "state_note": "Lead-only (same)"},
  "SKU-GT019": {"official": None,
      "offers": [{"seller": "livecards", "role": "Reseller", "price": 10.91, "cur": "USD", "note": "Genshin crystals pack $10.91 (listing mixes 300+30 and 1980+260 packs — identity ambiguous, likely regional-arbitrage top-up)", "evidence": EV, "identity_flag": "identity-ambiguous"}]},
  "SKU-GT020": {"official": None,
      "offers": [{"seller": "livecards", "role": "Reseller", "price": 10.91, "cur": "USD", "note": "same listing as GT019 — 1980+260 crystals at $10.91 if title-read correct (vs official $29.99) — needs page verification", "evidence": EV, "identity_flag": "identity-ambiguous"}]},
  "SKU-GT039": {"official": {"seller": "Xbox/MiHoYo store", "price": 4.99, "cur": "USD", "note": "Blessing of the Welkin Moon $4.99 (xbox.com product page snippet)", "evidence": EVO},
      "offers": []},

  # ═════════ Game Keys ═════════
  "SKU-GK001": {"official": None, "offers": [], "state_note": "Lead-only: FC 26 price not isolated in snippets this run"},
  "SKU-GK002": {"official": None, "offers": [], "state_note": "Lead-only (same)"},
  "SKU-GK003": {"official": {"seller": "Rockstar (gameboost-cited)", "price": 29.99, "cur": "USD", "note": "official price dropped $59.99 → $29.99 (gameboost statement 09/2026)", "evidence": EVN},
      "offers": [
        {"seller": "GameBoost (allkeyshop-tracked)", "role": "Marketplace", "price": 9.71, "cur": "USD", "note": "GTA 5 PC cheapest $9.71", "evidence": EV},
        {"seller": "loaded.com", "role": "Authorized reseller", "price": 6.79, "cur": "USD", "note": "GTA V Enhanced Rockstar key ~$6.79 (snippet formatting ambiguous '$ 6 7.99' — verify on page)", "evidence": EV, "identity_flag": "price-format-ambiguous"}]},
  "SKU-GK004": {"official": {"seller": "Steam (gocdkeys-cited)", "price": 59.99, "cur": "USD", "note": "Elden Ring Steam price ~$59.99 (implied by '34% below Steam' at $46.58 hmm — 46.58/0.66 ≈ 70.6; cited-basis ambiguous)", "evidence": EVN, "identity_flag": "official-implied"},
      "offers": [
        {"seller": "Eneba (allkeyshop-tracked)", "role": "Marketplace", "price": 46.44, "cur": "USD", "note": "Elden Ring PC £34.28 at Eneba (31.4% off)", "evidence": EV},
        {"seller": "Gocdkeys", "role": "Marketplace", "price": 46.58, "cur": "USD", "note": "Elden Ring Steam key from $46.58", "evidence": EV}]},
  "SKU-GK005": {"official": None, "offers": [], "state_note": "Lead-only: Cyberpunk price not isolated this run"},
  "SKU-GK006": {"official": None, "offers": [], "state_note": "Noise-rejected: results were other games (Call of the Sea, UNI2 DLC)"},
  "SKU-GK007": {"official": {"seller": "Steam (gg.deals-cited)", "price": 59.99, "cur": "USD", "note": "BG3 full Steam price $59.99 (gg.deals news)", "evidence": EVN},
      "offers": []},
  "SKU-GK008": {"official": None, "offers": [], "state_note": "No valid offer: results were 1984 magazine archive (noise)"},
  "SKU-GK009": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GK010": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-GK014": {"official": None,
      "offers": [
        {"seller": "Kinguin", "role": "Marketplace", "price": 19.97, "cur": "USD", "note": "CS2 Prime Status Upgrade (Steam Gift/DLC listing) $19.97 — page context mixes CS:CZ; identity partially matched", "evidence": EV, "identity_flag": "identity-partial"},
        {"seller": "huskyboost", "role": "Gray top-up service", "price": 15.0, "cur": "USD", "note": "CS2 Prime via Argentina $15-USD Steam-balance method (regional arbitrage)", "evidence": EV}]},
  "SKU-GK017": {"official": None,
      "offers": [{"seller": "gg.deals Keyshops", "role": "Price comparison", "price": 50.07, "cur": "USD", "note": "MHW keyshops $50.07 (from DLC-page sidebar — page-context ambiguous)", "evidence": EV, "identity_flag": "page-context-ambiguous"}]},
  "SKU-GK018": {"official": None,
      "offers": [{"seller": "Kinguin (KeysForAll)", "role": "Marketplace", "price": 21.48, "cur": "USD", "note": "AC Shadows CD key lowest $21.48 ('was $23.87, save $2.39')", "evidence": EV}]},
  "SKU-GK019": {"official": None,
      "offers": [{"seller": "Driffle (allkeyshop sidebar)", "role": "Marketplace", "price": 34.28, "cur": "USD", "note": "Black Myth Wukong $34.28 at Driffle (sidebar-sourced)", "evidence": EV}]},
  "SKU-GK023": {"official": None, "offers": [],
      "state_note": "No valid 12-month offer: results were monthly/1-month listings (loaded 1-mo GPU non-stackable $17.69 documented as adjacent identity — belongs to SKU-GK021 family)"},
  "SKU-GK024": {"official": {"seller": "Microsoft (G2A-cited plan table)", "price": 13.99, "cur": "USD", "note": "PC Game Pass $13.99/mo per G2A plan table — hmm official restructure tiers; direct verification pending", "evidence": EVN, "identity_flag": "verify-pending"},
      "offers": [{"seller": "Eneba", "role": "Marketplace", "price": 6.06, "cur": "USD", "note": "PC Game Pass 1-month TRIAL from $6.06 (trial identity — NOT full month)", "evidence": EV, "identity_flag": "trial-identity"}]},
  "SKU-GK025": {"official": {"seller": "Sony (G2A-cited)", "price": 24.99, "cur": "USD", "note": "PS+ Essential 3 months $24.99 ($8.33/mo)", "evidence": EVN},
      "offers": []},
  "SKU-GK026": {"official": {"seller": "Sony (G2A-cited)", "price": 79.99, "cur": "USD", "note": "PS+ 12 months $79.99 (Essential tier)", "evidence": EVN},
      "offers": []},

  # ═════════ Software ═════════
  "SKU-SW002": {"official": None, "offers": [], "state_note": "No valid offer: Win11 Home results were noise (eBay/justanswer/gist)"},
  "SKU-SW003": {"official": None,
      "offers": [{"seller": "Wincdkey (allkeyshop-tracked)", "role": "Key reseller", "price": 1.02, "cur": "USD", "note": "Windows 10 Pro £0.75 (~$1.02) — gray-key floor documented", "evidence": EV}]},
  "SKU-SW007": {"official": None,
      "offers": [{"seller": "Keys4us (allkeyshop-tracked)", "role": "Key reseller", "price": 0.60, "cur": "USD", "note": "Office 2024 Pro Plus $0.60 — consistent with Keyforsteam €0.56 prior-run observation (batch-1 corroboration)", "evidence": EV}]},
  "SKU-SW008": {"official": None,
      "offers": [{"seller": "Gocdkeys", "role": "Marketplace", "price": 61.24, "cur": "USD", "note": "M365 Personal 12-month $61.24 (no fees)", "evidence": EV}]},
  "SKU-SW009": {"official": None, "offers": [], "state_note": "Lead-only: M365 Family price not isolated this run"},
  "SKU-SW011": {"official": {"seller": "Adobe", "price": 659.88, "cur": "USD", "note": "CC All Apps ~$59.99/mo annual-equivalent; first-year -40% promo documented (macrumors 05/2025)", "evidence": EVN},
      "offers": [{"seller": "Klarna-listed merchant", "role": "Reseller", "price": 239.88, "cur": "USD", "note": "'Adobe CC Pro 12 Month Subscription $239.88 ($21.54/mo)' — identity ambiguity (CC Pro ≠ All Apps) — verification needed", "evidence": EV, "identity_flag": "identity-ambiguous"}]},

  # ═════════ eSIM ═════════
  "SKU-ES002": {"official": None,
      "offers": [{"seller": "Airalo", "role": "eSIM provider (Notion-listed)", "price": 4.0, "cur": "USD", "note": "United States eSIM 'from $4.00' (title-level; package-to-price mapping needs page verification; 3-day unlimited $11.50, 30-day unlimited $68 also on page)", "evidence": EV, "identity_flag": "package-mapping-pending"}]},
  "SKU-ES004": {"official": None,
      "offers": [{"seller": "Airalo (esimdb-tracked)", "role": "eSIM provider (Notion-listed)", "price": 24.0, "cur": "USD", "note": "KSA 10GB/7d $24.00 ($2.40-2.45/GB) — 7-day validity (SKU specifies 30d — adjacent identity)", "evidence": EV, "identity_flag": "adjacent-duration"}]},
  "SKU-ES006": {"official": None,
      "offers": [{"seller": "eSIMCard", "role": "eSIM provider", "price": 7.85, "cur": "USD", "note": "Middle East/Global Lite 3GB/30d $7.85 ($2.62/GB)", "evidence": EV}]},
  "SKU-ES007": {"official": None, "offers": [], "state_note": "No valid offer: Egypt 5GB results were Greece/Turkey pages (noise)"},
  "SKU-ES010": {"official": None, "offers": [], "state_note": "No valid offer: Europe 10GB results were noise"},
  "SKU-ES012": {"official": None,
      "offers": [{"seller": "Airalo", "role": "eSIM provider (Notion-listed)", "price": 4.5, "cur": "USD", "note": "global 1GB/7d from $4.50 (blog-documented 'Airalo plans start at $4.50 for 1GB/7 days')", "evidence": EVN}]},
  "SKU-ES013": {"official": None,
      "offers": [{"seller": "ByteSim (blog-documented)", "role": "eSIM provider", "price": 25.0, "cur": "USD", "note": "global 10GB $25-50 range (range not point price)", "evidence": EVN, "identity_flag": "range-not-point"}]},

  # ═════════ SMM ═════════
  "SKU-SM001": {"official": None,
      "offers": [{"seller": "SMM panels (aggregated)", "role": "Panel floor", "price": 0.01, "cur": "USD", "note": "IG followers from $0.01-0.09 per 1000 (panel floor; quality/retention unguaranteed)", "evidence": EVN}]},
  "SKU-SM004": {"official": None,
      "offers": [{"seller": "smmtrustpanel", "role": "Panel", "price": 1.5, "cur": "USD", "note": "TikTok followers ~$1.50/1000 (per-1000 rate table)", "evidence": EV}]},
  "SKU-SM006": {"official": None,
      "offers": [{"seller": "smmpwr (aggregated)", "role": "Panel", "price": 0.06, "cur": "USD", "note": "YT subscribers from $0.06-0.10 per 1000 (15 services listed)", "evidence": EV}]},
  "SKU-SM009": {"official": None,
      "offers": [{"seller": "nicesmmpanel", "role": "Panel", "price": 0.07, "cur": "USD", "note": "TG members from $0.07-0.11 per 1000 (poll votes $0.11)", "evidence": EV}]},

  # ═════════ Virtual Numbers ═════════
  "SKU-VN002": {"official": None, "offers": [], "state_note": "No clean 1-time OTP price: quackr rental (price unclear), callhippo $18/user/mo = business lines (identity mismatch)"},
  "SKU-VN005": {"official": None, "offers": [], "state_note": "Lead-only: no isolated USA TG OTP price in snippets (sms-activate floor documented in batch 1: RU ~$0.5-1.2 family)"},
  "SKU-VN006": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN007": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN008": {"official": None,
      "offers": [{"seller": "PvaPins", "role": "OTP service", "price": 1.61, "cur": "USD", "note": "Egypt Telegram OTP number from $1.61", "evidence": EV}]},
  "SKU-VN009": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN010": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN011": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN012": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN013": {"official": None, "offers": [], "state_note": "No valid offer: results were spam pages (documented as search-quality limit)"},
  "SKU-VN014": {"official": None,
      "offers": [{"seller": "tiger-sms (Fotka page reference)", "role": "OTP service", "price": 0.006, "cur": "USD", "note": "Indonesia number floor $0.006 (Fotka service page — documents ID OTP price floor, not WhatsApp-specific)", "evidence": EV, "identity_flag": "adjacent-service (Fotka ≠ WhatsApp)"}]},
  "SKU-VN015": {"official": None,
      "offers": [{"seller": "MoreMins", "role": "Number rental", "price": 0.99, "cur": "USD", "note": "WA virtual number from $0.99/MONTH (rental model — SKU assumes 1-time OTP; adjacent identity)", "evidence": EV, "identity_flag": "rental-model-adjacent"}]},
  "SKU-VN016": {"official": None,
      "offers": [{"seller": "Fanytel", "role": "Number rental", "price": 0.99, "cur": "USD", "note": "US/UK number $0.99/mo ($9.99/yr) — rental model adjacent", "evidence": EV, "identity_flag": "rental-model-adjacent"}]},
  "SKU-VN017": {"official": None,
      "offers": [{"seller": "tiger-sms (Fotka page reference)", "role": "OTP service", "price": 0.006, "cur": "USD", "note": "same ID floor as VN014 (Egypt WA not isolated)", "evidence": EV, "identity_flag": "adjacent-service"}]},
  "SKU-VN020": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN021": {"official": None, "offers": [],
      "state_note": "Noise-rejected: Google Voice business $10/user/mo is a phone line product, not OTP"},
  "SKU-VN022": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN023": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN024": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN025": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN026": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN027": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN028": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN029": {"official": None, "offers": [], "state_note": "Lead-only"},
  "SKU-VN030": {"official": None, "offers": [],
      "state_note": "Noise-rejected: Google Voice business listing (same as VN021)"},
  "SKU-VN031": {"official": None, "offers": [], "state_note": "Lead-only"},

  # ═════════ Digital Subscriptions ═════════
  "SKU-DS001": {"official": {"seller": "Netflix (news-documented)", "price": 8.99, "cur": "USD", "note": "Standard with Ads $8.99/mo (raised from $7.99, 03/2026 news — corroborates batch-1)", "evidence": EVN},
      "offers": []},
  "SKU-DS005": {"official": None, "offers": [],
      "state_note": "Lead-only: 'private account' results carried no price (gray private-account market documented in MEC-2.0 economics)"},
  "SKU-DS008": {"official": None,
      "offers": [{"seller": "TG seller SellerDealer (telemetr.io-documented)", "role": "Gray Telegram seller", "price": 1.37, "cur": "USD", "note": "Spotify Family seat ₹119 (~$1.37) India gray — corroborates MEC-2.0 supply-chain economics (family-seat extraction model)", "evidence": EV}]},
  "SKU-DS009": {"official": None, "offers": [], "state_note": "Lead-only: TR Spotify 12-mo price not isolated this run (India ₹799/yr documented in MEC-2.0)"},
  "SKU-DS012": {"official": None, "offers": [], "state_note": "No valid offer: results were noise (airbnb/satellite-internet pages)"},
  "SKU-DS013": {"official": {"seller": "Disney+ (official page snippet)", "price": 9.99, "cur": "USD", "note": "Standard with Ads $9.99/mo (page also shows $18.99 Standard / $25.99 tiers — mapping needs verification)", "evidence": EVO, "identity_flag": "tier-mapping-partial"},
      "offers": []},
  "SKU-DS014": {"official": None,
      "offers": [{"seller": "Kinguin (CdKeyMarkt)", "role": "Marketplace", "price": 144.53, "cur": "USD", "note": "Disney+ 12-month Standard card DE $144.53 (region DE; Standard not Premium — adjacent identity)", "evidence": EV, "identity_flag": "adjacent-identity (DE, Standard)"}]},
  "SKU-DS015": {"official": None, "offers": [], "state_note": "No valid offer: Max results were math-journal pages (noise)"},
  "SKU-DS016": {"official": None, "offers": [], "state_note": "No valid offer: Hulu results were real-estate/2020-article noise"},
  "SKU-DS017": {"official": None, "offers": [], "state_note": "Lead-only: Prime Video price not isolated this run"},
  "SKU-DS022": {"official": {"seller": "Apple (official page snippet)", "price": 6.99, "cur": "USD", "note": "'just $6.99/month, first month free' — apple.com snippet wording suggests promo/annual-billing price; standard Individual $10.99 known prior — direct verification pending", "evidence": EVO, "identity_flag": "promo-wording-ambiguous"},
      "offers": []},
  "SKU-DS026": {"official": {"seller": "NordVPN (blog-documented)", "price": 55.08, "cur": "USD", "note": "1-year plan $4.59-5.99/mo range (≈$55-72/yr); monthly $12.99", "evidence": EVN},
      "offers": []},
  "SKU-DS029": {"official": None, "offers": [], "state_note": "Lead-only: iCloud+ tier prices not isolated in snippets"},
  "SKU-DS030": {"official": None, "offers": [], "state_note": "Lead-only (same)"},
  "SKU-DS031": {"official": {"seller": "Google (news-documented)", "price": 1.99, "cur": "USD", "note": "Google One 100GB $1.99/mo ($19.99/yr)", "evidence": EVN},
      "offers": []},
  "SKU-DS048": {"official": {"seller": "Google India (MEC-2.0 documented)", "price": 3.44, "cur": "USD", "note": "YT Premium India ₹299 family / individual ₹149 (~$1.72) — inherited MEC-2.0 observation (26/09 queries)", "evidence": "Documented (MEC-2.0 run, 27/09)"},
      "offers": []},
  "SKU-DS049": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit) — EG Netflix price not retrieved"},
  "SKU-DS050": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit) — SA Netflix price not retrieved"},

  # ═════════ API Services (rate-limited queries — honest states) ═════════
  "SKU-AP002": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit)"},
  "SKU-AP003": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit)"},
  "SKU-AP005": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit); role verified in batch 1 (API/Distributor)"},
  "SKU-AP006": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit); role verified in batch 1"},
  "SKU-AP007": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit)"},
  "SKU-AP008": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit)"},
  "SKU-AP009": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit)"},
  "SKU-AP010": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit)"},
  "SKU-AP016": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit); Turgame wholesale verified live in batch 1"},

  # ═════════ Digital Subscriptions rate-limited ═════════
  "SKU-DS038": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit); TG Premium 3-mo"},
  "SKU-DS040": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit); TG Stars 100"},
  "SKU-DS041": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit); TG Stars 1000"},
  "SKU-DS043": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit); Nitro 12-mo"},
  "SKU-DS061": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit); ExpressVPN 12-mo"},
  "SKU-DS062": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit); Surfshark 24-mo"},
  "SKU-DS063": {"official": None, "offers": [], "rate_limited": True, "state_note": "Query deferred (rate-limit); Canva annual"},
}
